spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/musiccloud
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    # show_sql과는 다르게 logger를 통해서 로그를 sql 로그를 찍기 때문에 이걸 써야한다.
    org.hibernate.SQL: debug
    # 쿼리 파라미터 출력
    org.hibernate.type: trace
